theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
        - search.suggest
        - search.highlight
    palette:
        - scheme: default
          primary: deep orange
    logo: "images/delta.png"  # logo in top left
    favicon: "images/delta.svg"

site_name: sensitivity_torch
site_description: The documentation for the sensitivity_torch package.
site_author: Robert Dyro 
site_url: https://rdyro.github.io/sensitivity_torch/

repo_url: https://github.com/rdyro/sensitivity_torch
repo_name: rdyro/sensitivity_torch

strict: false

markdown_extensions:
  toc:
    toc_depth: 2

extra_css:
  - _static/custom_css.css

plugins:
    - search 
    - autorefs
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import pytkdocs_tweaks
                    - pytkdocs_tweaks.main()
                options:
                    inherited_members: true
                    show_root_heading: true
                    show_if_no_docstring: true
                    show_signature_annotations: false
                    heading_level: 4
                    members_order: source
nav:
    - Overview: 'index.md'
    - Installation: 'installation.md'
    - Tour: 'tour.md'
    - Full API:
        - 'api/sensitivity.md'
        - 'api/optimization.md'
        - 'api/utils.md'
        - 'api/misc.md'
